apiVersion: v1
kind: PersistentVolume
metadata:
  name: open5gs
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/volumes/open5gs